my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolioapp.urls'))

]

portfolioapp/urls.py
from django.urls import path

from . import views

app_name = 'portfolio_app'

urlpatterns = [
           path('', views.homepage, name='home'),
           path('about/', views.about, name='about'),
           path('resume/', views.resume, name='resume'),
           path('research/', views.research, name='research'),
           path('publications/', views.publication, name='publication'),
           path('presentation/', views.presentation, name='presentation'),
           path('resources/', views.resource, name='resources'),
           path('gallery/', views.gallery, name='gallery'),
]

portfolioapp/models.py
from django.db import models

# Create your models here.

class ContactForm(models.Model):
    Name = models.CharField(max_length=100)
    Email = models.EmailField(blank=True)
    Message = models.TextField()

    def __str__(self):
        return self.Name

portfolioapp/forms.py
from django import forms

from .models import ContactForm

class MessageForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields=['Name', 'Email', 'Message']

        widgets = {
            'Name': forms.TextInput(attrs ={'class': 'form-label'}),
            'Email': forms.EmailInput(attrs ={'class': 'form-label'}),
            'Message': forms.Textarea(attrs ={'class': 'form-label'}),
        }

        

# class ContactForm1(forms.Form):
#     subject = forms.CharField(max_length=100)
#     email = forms.EmailField(required=False)
#     message = forms.CharField(widget=forms.Textarea)

portfolioapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ContactForm
from .forms import MessageForm
from django.http import HttpResponse
from django.contrib import messages
from django.core.mail import send_mail

# Create your views here.

def homepage(request):
    return render(request, 'portfolioapp/index.html', {})


# def about(request):
#     if request.method=="POST":
#         contact = ContactForm()
#         name=request.POST.get('name')
#         email=request.POST.get('email')
#         message = request.POST.get('message')
#         contact.Name=name
#         contact.Email = email
#         contact.Message = message
#         contact.save()
#         contact = ContactForm()
#         # if contact.is_valid(): 
#         #    contact.save()
#         #    contact = ContactForm()

#         return render(request, 'portfolioapp/about.html', {'name':name})

#     else:
#         return render(request, 'portfolioapp/about.html', {})   

def about(request):
    form = MessageForm(request.POST or None)
    if form.is_valid():
        name = request.POST['Name']
        email = request.POST['Email']
        message = request.POST['Message']
        form.save()
        form = MessageForm()
        send_mail(
            name,
            message +' '+ 'sent by' +" "+ email,
            email,
            ['pooja.kc3062@gmail.com']
           )
        #messages.success(request, ("Email sent successfully"))   
        return render(request, 'portfolioapp/about.html', {'name':name})
        # send email

    else:    

        context = {
           'form' : form
            }    
        return render(request, 'portfolioapp/about.html', context)

def resume(request):
    return render(request, 'portfolioapp/resume.html', {})

def research(request):
    return render(request, 'portfolioapp/research.html', {})   

def publication(request):
    return render(request, 'portfolioapp/publications.html', {}) 

def presentation(request):
    return render(request, 'portfolioapp/presentation.html', {}) 
      
def resource(request):
    return render(request, 'portfolioapp/coding.html', {})  

def gallery(request):
    return render(request, 'portfolioapp/gallery.html', {})       

portfolioapp/templates/portfolioapp/about.html
{% extends 'portfolioapp/base.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'styles.css' %}">
<script src='https://www.google.com/recaptcha/api.js'></script>




{% block content %}

<div class="content-wrapper">   <!-- main body content-->
  <div class="two-column-wrapper">
    <div class="profile-image-wrapper">
        <img src="{% static 'portfolio/about-image2.jpg' %}" alt="">
    </div>

    <div class="profile-content-wrapper">
      <h1>SHAMBHU KC</h1>
      <h3>Doctoral Candidate | Physics | Material Science | Data Analysis | Artificial Intelligence | Web Design </h3>
      <p>Shambhu KC is a result-oriented and motivated doctoral student in experimental Condensed Matter Physics at the University of Alabama. He is currently working under the guidance of
        Dr. Patrick LeClair, and Dr. Arunava Gupta. He recieved B.Sc. in Physics, Statistics, 
        and Mathematics in 2010 from Tribhuvan University, Nepal. Then he recieved M.Sc. in Physics in 2013 from Tribhuvan University, Nepal, where he worked under the supervision of Dr. Binil Aryal
        to complete his Master's thesis, titled <b>Interaction Between Ambient ISM and AGB Starts at Lattitude -1&deg</b>. He also obtained his second M.Sc. in experimental Condensded Matter Physics from the 
        University of Alabama in 2019.
      </p> 

      <p>Shambhu's main research is focused on the discovery of novel half-metallic Heusler compounds for potential spintronic applications. He excels in sample preparation, characterization,
          and high throughput data analysis. Besides the research activites, Shambhu enjoys learning and trying new skills, exploring new advancemnts made in the electronic device components. He has received Outstanding Graduate Student Research by a Doctoral Student Award in 2020
          from the department of Physics and Astronomy, and
          in the same year he also received Graduate Council Fellowship from the Graduate School of the University of Alabama.
      </p>
        
      <p>
          Shambhu is afiliated with American Physical Society (APS), American Vacuum Society (AVS), and IEEE Magnetics Society. He is also an acting Condensed Matter Experiment Liaison
          in Physics Astronomy Graduate Student Association (PAGSA) of University of Alabama.
      </p><hr>

      <p>
          If you have any suggestions or questions for Shambhu please connect to him via any of the social sites listed at the bottom. You can also send direct message by using the form below.
      </p>
      
        
        
         <!-- <div class="form-container">
           <form class="form-control" method = "post"> {% csrf_token %}
            <div class="form-group">
              <label for="fname">Your Name</label>
              <input name ='name' type="text" id="fname" class="form-control" placeholder="Enter your name [Optional]"/>

              <label for="exampleInputEmail">Your email</label>
              <input name = 'email' type="text" class="form-control" id="exampleInputEmail" placeholder="example@email.com [optional]"/>

              <label for="typemessage">Message</label>
              <textarea name = 'message' class="form-textarea" id='typemessage' placeholder="Type your message here..."></textarea>

            </div>
            <input type = "submit" value="Send Message"/>
           </form>
         </div> -->

      {% if name %} 
        <center>
          <div class="thanks-note">
            <h3> Thank you {{ name }} for sending your message!</h3>
            <p>Your message has been recieved and Shambhu will get in touch with you shortly ..... </p>
            <a href = "{% url 'portfolio_app:about' %}"><input type ='submit' value = 'Send Again' class="button" /></a>
          </div>
          
        </center>

      {% else %}
        <div class = "mb-3">
          <form method='POST'> {% csrf_token %}
            {{form.as_p}}        

            <input type='submit' value='Send Message' class="button" />

            <div class="g-recaptcha" data-sitekey="6LdXYo0aAAAAAJrZnX23sFr1WsdVYq7Lvo25vLuW"></div>
          </form> 
        </div>     

      {% endif %}   
         
    </div>
  </div>
</div>

{% endblock %}


   

portfolioapp/templates/portfolioapp/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset='UTF-8'>
  
  <title>Shambhu's Website</title>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  

</head>
<body>
    <div class="container">
    <nav>
      <div class="nav-wrapper">
        <div class="left-side">
          <div class="nav-link-wrapper active-nav-link">
            <a href="{% url 'portfolio_app:home' %}">Home</a>     <!-- the "protfolio_app" is the app name defined in urls.py inside app and "home" is name of the url path-->
          </div>
  
          <div class="nav-link-wrapper">
            <a href="{% url 'portfolio_app:about' %}">About</a>
          </div>
          
        </div>
  
        <div class="right-side">
          <div class="brand">
            SHAMBHU KC
          </div>
        </div>
      </div>
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <div class="footer-content">
          <h3>Stay Connected</h3>
          <ul class="links">
            <li><a href="https://www.facebook.com/shambhu.kc" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://www.instagram.com/samvu.kc_" target="_blank"><i class="fa fa-instagram"></i></a></li>
            <li><a href="https://twitter.com/shambhu_kc46" target="_blank"><i class="fa fa-twitter" target="_blank"></i></a></li>
            <li><a href="mailto:skc@crimson.ua.edu" target="_blank"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="https://www.youtube.com/channel/UCe86OpHOvMYwGHGuRc2bsOQ" target="_blank"><i class="fa fa-youtube"></i></a></li>
            <li><a href="https://www.linkedin.com/in/shambhu45/" target="_blank"><i class="fa fa-linkedin-square fa-10x"></i></a></li>
            <li><a href="https://www.researchgate.net/profile/Shambhu-Kc" target="_blank"><i class="fab fa-researchgate"></i></a></li>
          </ul>
    
        </div>
        <div class="footer-bottom">
          <p>copyright &copy;2021 Shambhu KC</p>
        </div>
      </footer>
</body>

<script>
    const portfolioItems = document.querySelectorAll('.portfolio-item-wrapper');
  
    portfolioItems.forEach(portfolioItem => {
      portfolioItem.addEventListener('mouseover', () => {
        console.log(portfolioItem.childNodes[1].classList)
        portfolioItem.childNodes[1].classList.add('image-blur');
      });
  
      portfolioItem.addEventListener('mouseout', () => {
        console.log(portfolioItem.childNodes[1].classList)
        portfolioItem.childNodes[1].classList.remove('image-blur');
      });
    });
  
  </script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</html>

portfolioapp/templates/portfolioapp/coding.html
{% extends 'portfolioapp/base.html' %}

{% load static %}



{% block content %}

   <div class="coding-wrapper">
     <p><b>Research related</b></p><hr>
     <ul>
      <li><a href="https://github.com/skc46/Alloys_preparation/blob/master/bulk_sample_wt_cal.ipynb", target="_blank">Calculate the weights of elements to make bulk ingots of Heusler alloys</a></li>
     </ul>

     <p><b>Machine Learning/ Deep Learning</b></p><hr>
     <ul>
      <li><a href="https://github.com/skc46/Machine_learning_notebooks/blob/master/Neuclear_magnetic_resonance%20with%20Spin%20echo.ipynb",
      target="_blank">Using Deep Neural Network to predict coupling strength, length of the neuclear interaction and dissipation time of nuclear spins from Neuclear
      magnetic resonance (NMR) Spin Echo Animation curves.</a><br></li>


      <li><a href="https://github.com/skc46/Machine_learning_notebooks/blob/master/CNN_CERNparticle_identification.ipynb", target="_blank">
      Use of Convolutional Neural Network (CNN) to identify the paticles in Large Hadron Collider (LHC) collisions</a></li>
     </ul>

     <p><b>Webpage</b></p><hr>
     <ul>
      <li> <a href="https://github.com/skc46/portfolio", target="_blank">Codes related to the development of this website</a></li>
     </ul>
   </div>

   <div><h1>More codes coming soon</h1></div>


{% endblock %}

portfolioapp/templates/portfolioapp/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>footer</title>
    <link rel="stylesheet" href="style_01.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <footer>
        <div class="footer-content">
            <h3>code opacity</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo iste corrupti doloribus odio sed!</p>
            <ul class="socials">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                <li><a href="https://www.linkedin.com/in/shambhu45/"><i class="fa fa-linkedin-square"></i></a></li>
            </ul>
        </div>
        <div class="footer-bottom">
            <p>copyright &copy;2020 codeOpacity. designed by <span>nethunt</span></p>
        </div>
    </footer>
</body>
</html>

portfolioapp/templates/portfolioapp/gallery.html
{% extends 'portfolioapp/base.html' %}

{% load static %}




{% block content %}

<div class="image-wrapper">
      <div class="avs">
         <figure class="avs-award"><a href="#">
            <img  src="{% static 'portfolio/avs-presentation.JPG' %}" />
          
         </a> 
          <figcaption>Presenting my work on Co<sub>1.5</sub>Ti<sub>0.5</sub>FeGe thin-films at AVS 66th International 
            Symposium & Exhibition 2019, Columbus, OH USA </figcaption>
          </figure>

          <figure class="avs-award"><a href="#">
            <img src="{% static 'portfolio/Falicov-Award.jpg' %}" />
            </a>
            <figcaption>Leo Falicov-Award Ceremony at AVS 66th International 
                Symposium & Exhibition 2019, Columbus, OH USA<a href ="https://avs.org/awards/division-group-student-awards/magnetic-interfaces-nanostructures-division-the-le/">[source]</a> </figcaption>
          </figure>

        </div>
        
        
            

      <figure class="APS-2019">
        <img src="{% static 'portfolio/APS1.JPG' %}" alt="">
        <img src="{% static 'portfolio/APS3.JPG' %}" alt="">
        <figcaption>Presenting poster at APS March Meeting, 2019, Boston, MA USA</figcaption>
      </figure> 

      <figure class="mint-poster"><a href="#"><img src="{% static 'portfolio/mint_poster.jpg' %}" alt=""></a>
        <figcaption>Presenting two posters at MINT Review, 2018, Tuscaloosa, AL USA</figcaption>
      </figure>
  </div>

{% endblock %}


   

portfolioapp/templates/portfolioapp/index.html
{% extends "portfolioapp/base.html" %}

{% load static %}


{% block content %}
    <div class="content-wrapper">
      <div class="portfolio-items-wrapper">

        <a href="{% url 'portfolio_app:resume' %}">
          <div class="portfolio-item-wrapper">
            <div class="portfolio-img-background" style="background-image:url('{% static "portfolio/profile_pic.jpg" %}')"></div>
            <div class="img-text-wrapper">
              <div class="subtitle">Resume</div>
            </div>
          </div>
          </a>


        <a href="{% url 'portfolio_app:research' %}">
          <div class="portfolio-item-wrapper">
            <div class="portfolio-img-background" style="background-image:url('{% static "portfolio/research.jpg" %}')"></div>
            <div class="img-text-wrapper">
              <div class="subtitle">Research</div>
            </div>
          </div>
        </a> 
        
        
        <a href="{% url 'portfolio_app:publication' %}">
          <div class="portfolio-item-wrapper">
            <div class="portfolio-img-background" style="background-image:url('{% static "portfolio/publications.jpg" %}')"></div>
            <div class="img-text-wrapper">
              <div class="subtitle">Publications</div>
            </div>
          </div>
        </a> 
        

        <a href = "{% url 'portfolio_app:presentation' %}">
          <div class="portfolio-item-wrapper">
            <div class="portfolio-img-background" style="background-image:url('{% static "portfolio/presentations.jpg" %}')"></div>
            <div class="img-text-wrapper">
              <div class="subtitle">Presentations</div>
            </div>
          </div>
        </a>

        <a href = "{% url 'portfolio_app:resources' %}">
          <div class="portfolio-item-wrapper">
            <div class="portfolio-img-background" style="background-image:url('{% static "portfolio/coding.jpg" %}')"></div>
            <div class="img-text-wrapper">
              <div class="subtitle">Resources</div>
            </div>
          </div>
        </a>
        
  
        <a href = "{% url 'portfolio_app:gallery' %}">
          <div class="portfolio-item-wrapper">
            <div class="portfolio-img-background" style="background-image:url('{% static "portfolio/gallery.jpg" %}')"></div>
            <div class="img-text-wrapper">
              <div class="subtitle">Gallery</div> 
            </div>
          </div>
        </a>
        


      </div>
    </div>
    
{% endblock %}

  
  

portfolioapp/templates/portfolioapp/presentation.html
{% extends "portfolioapp/base.html" %}

{% load static %}
           
{% block content %}           
           
           
   <div class="presen-container">
      <h1>Presentations</h1>
      <hr>
      <div class="presentation-wrapper">
         <p>
            <b>(Poster-Presenter)</b> Co<sub>2</sub>Fe<sub>1.25</sub>Ge<sub>0.75</sub>: the perfect material for spintronics?<br>
             International Winter School - 2020 on Frontiers in Materials Science - A virtual Event 2020, India 
          </p>

      </div>

      <div class="presentation-wrapper">
         <p>
            <b>(Oral-Presenter)</b> Interplay Between Mn, Fe, and Co in the Co<sub>2</sub>FeGe Alloy to Design Novel Single-Phase Compounds with Potential Spintronic Application<br>
            MMM2020 Virtual Conference 2020, USA
         </p>
      </div>

      <div class="presentation-wrapper">
         <p>
            <b>(Oral-Presenter)</b> Stabilizing Single-Phase Microstructures and Tuning Half-Metallic Character in Heusler Alloys by Following a Novel 
            Route of Substitution<br>
            University of Alabama at Birmingham 2020, Birmingham, AL USA
         </p>
      </div>

      <div class="presentation-wrapper">
         <p>
            <b>(Oral-Presenter)</b> Substrate Dependent Structural and Magnetic Properties of Epitaxial Co<sub>1.5</sub>Ti<sub>0.5</sub>FeGe 
            Heusler Alloy Thin-films<br>
            AVS 66th International Symposium & Exhibition 2019, Columbus, OH USA
         </p>
      </div>

      <div class="presentation-wrapper">
         <p>
            <b>(Poster-Presenter)</b> Structural, Magnetic, Electronic, and Mechanical Properties of the Co<sub>2-x</sub>Ti<sub>x</sub>FeGe Alloy Series<br>
            APS March Meeting 2019, Boston, OH USA
         </p>
      </div>

      <div class="presentation-wrapper">
         <p>
            <b>(Poster-Presenter)</b> Structural, Magnetic and Electronic Properties of the Co<sub>2-x</sub>Ti<sub>x</sub>FeGe Alloy Series with Possible Half-Metallic Behavior<br>
            MINT Reivew, University of Alabama 2018, Tuscaloosa, AL USA
         </p>
      </div>

      <div class="presentation-wrapper">
         <p>
            <b>(Poster-Presenter)</b> Epitaxial Growth and Characterization of VO<sub>2</sub> Thin Films on TiO<sub>2</sub> Substrates<br>
            MINT Reivew, University of Alabama 2018, Tuscaloosa, AL USA
         </p>

      </div>

      <div class="presentation-wrapper">
         <p>
            <b>(Poster-Presenter)</b> Fe<sub>x</sub>Co<sub>y</sub>TiGe: A Novel Quaternary Heusler<br>
            MINT Reivew, University of Alabama 2017, Tuscaloosa, AL USA
         </p>
      </div>

{% endblock %}            

portfolioapp/templates/portfolioapp/publications.html
{% extends 'portfolioapp/base.html' %}

{% load static %}

{% block content %}

<div class="pub-container">
  <h1>Publications</h1>
    <hr>
  <ol>
     <li>
      S. KC, R. Mahat, S. Budhathoki, S. Regmi, J. Y. Law, V. Franco, W. H. Butler, A. Gupta, P. LeClair<br>
      <a href = "#" >Interplay of Mn, Fe, and Co in Co<sub>2</sub>FeGe Heusler Alloy to Design Novel Single-Phase Compounds with Potential Spintronic Applications</a><br>
      In preparation (2021)
     </li>

     <li>
      S. KC, R. Mahat, S. Regmi, J. Y. Law, V. Franco, G. Mankey, W. H. Butler, A. Gupta, P. LeClair<br>
      <a href = "#" >Co<sub>2</sub>Fe<sub>1.25</sub>Ge<sub>0.75</sub>: A Single-phase Full Heusler Alloy with Highest Magnetic Moment and Highest Curie Temperature</a><br>
      In preparation (2021)
     </li>

     <li>
      S. KC, S. Budhathoki, R. Mahat, A. Sapkota, A. Rai, T. Evans, S. Regmi, T. Mewes, A. Hauser, G. Mankey, A. Gupta, P. LeClair<br>
      <a href = "#" >Substrate dependent properties of Co<sub>1.5</sub>Ti<sub>0.5</sub>FeGe thin films</a><br>
      In preparation (2021)
     </li>

     

     <li>
      N. Naghibolashrafi, S. KC, V. I. Hegde, J. Ma, A. Gupta, P. LeClair, W. H. Butler, C. Wolverton, A. W. Ghosh<br>
      <a href = "#" >Synthesis and Characterization of Co-Ti-Sn Alloys: Co<sub>1.5</sub>TiSn as Half Metal Based on the Fe<sub>1.5</sub>TiSb Prototype of Layered Heusler</a><br>
       Submitted (2020)
     </li>

     <li>
      S. Regmi, Z. Li, A. Srivastava, R. Mahat, S. KC, A. Rastogi, Z. Galazka, R. Datta, T. Mewes, and A. Gupta<br>
      <a href = "https://aip.scitation.org/doi/full/10.1063/5.0047865" target="_blank">Structural and magnetic properties of NiFe<sub>2</sub>O<sub>4</sub> thin films grown on isostructural lattice-matched substrates</a><br>
      Applied Physics Letters <strong>118</strong>, 152402 (2021)
     </li>

     <li>
      R. Mahat, S. KC, D. Wines, S. Regmi, U. Karki, Z. Li, F. Ersan, J. Law, C. Ataca, V. Franco, A. Gupta, P. LeClair<br>
      <a href="https://www.sciencedirect.com/science/article/pii/S0304885320323659" target="_blank">Influence of Cr-substitution on the structural, magnetic, electron transport, and mechanical properties of Fe3−xCrxGe Heusler alloys</a><br>
      Journal of Magnetism and Magnetic Materials <strong>521</strong>, 167398 (2021)
     </li>

     <li>
     R. Mahat, S. KC, D. Wines, F. Ersan, S. Regmi, U. Karki, R. White, C. Ataca, P. Padhan, A. Gupta, P. LeClair<br>
     <a href="https://www.sciencedirect.com/science/article/pii/S0925838820307660" target="_blank">Tuneable structure and magnetic properties in Fe<sub>3-x</sub>V<sub>x</sub>Ge alloys</a><br>
     Journal of Alloys and Compounds <strong>830</strong>, 154403 (2020)
     </li>

     <li>
     N. Naghibolashrafi, V. I. Hegde, S. KC, S. Keshavarz, S. Naghavi, J. Ma, A. Gupta, P. LeClair, W. H. Butler, C. Wolverton, K. Munira, D. Mazumdar, A. W. Ghosh<br>
     <a href="https://www.sciencedirect.com/science/article/pii/S0925838819346547" target="_blank">Structural and magnetic analyses of the FexCo1−xTiSb alloy system: Fe0.5Co0.5TiSb as a prototypical half-Heusler compound</a><br>
     Journal of Alloys and Compounds <strong>822</strong>, 153408 (2020)
     </li>

     <li>
      S. Budhathoki, A. Sapkota, K. M. Law, B. Nepal, S. Ranjit, S. KC, T. Mewes, A. J. Hauser<br>
      <a href="https://www.sciencedirect.com/science/article/pii/S0304885319326551" target="_blank">Low Gilbert damping and linewidth in magnetostrictive FeGa thin films</a><br>
      Journal of Magnetism and Magnetic Materials <strong>496</strong>, 165906 (2020)
     </li>

     <li>
      S. KC, R. Mahat, S. Regmi, A. Mukherjee, P. Padhan, R. Datta, W. H. Butler, A. Gupta, P. LeClair<br>
      <a href="https://journals.aps.org/prmaterials/abstract/10.1103/PhysRevMaterials.3.114406" target="_blank">Tunable properties and potential half-metallicity in (Co<sub>2-x</sub>Ti<sub>x</sub>)FeGe Heusler alloys: An experimental and theoretical investigation</a><br>
      Physical Review Materials <strong>3</strong>, 114406 (2019)
     </li>
  </ol>

</div>

{% endblock %}
          
          
          
          